# Generated by Django 3.2.7 on 2026-01-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SPORTS', 'Sports'), ('ARTS', 'Arts'), ('TECHNICAL', 'Technical'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(default='Campus', max_length=200)),
                ('max_participants', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('faculty_incharge', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
